[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.sel-protocol]
opt-level = 1
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
opt-level = 1
rpath = false
lto = true
overflow-checks = true
