[package]
name = "sel-protocol"
version = "0.1.0"
authors = ["Selenian Network"]
edition = "2021"
description = "Common helpers for sel-protocol"
repository = "https://github.com/selenian/sel"
homepage = "https://selenian.network"
documentation = "https://docs.selenian.network"
license = ""


[dependencies]
cw20 = { version = "1.0.0" }
cosmwasm-std = { version = "1.1.8", default-features = false }
cosmwasm-storage = { version = "1.1.8", default-features = false }
schemars = { version = "0.8.11" }
serde = { version = "1.0.148", default-features = false }
uint = { version = "=0.9.5" }

[profile.release]
overflow-checks = true
